# Files / File types

pre-commit:
  - ".pre-commit-config.yaml"

config:
  - "example.env"

submodules:
  - "**/*.gitmodules"

docker:
  - "**/Dockerfile"
  - "**/docker-compose*.y*ml"

pip dependencies:
  - "**/requirements.txt"

npm dependencies:
  - "frontend/package-lock.json"

python:
  - "**/*.py"

svelte:
  - "**/*.svelte"

typescript:
  - "**/*.ts"

# Subdirectories

actions:
  - ".github/**"

analog-output:
  - "analog_output/**"

auto-labeling:
  - "auto_labeling/**"

dhcp-server:
  - "dhcp_server/**"

documentation:
  - "documentation/**"

frontend:
  - "frontend/**"

inference-environment:
  - "inference_environment/**"

inline-inference:
  - "camera_connect_inline_inference/**"

inoyad-connector:
  - "inoyad_connector/**"

light-barrier:
  - "light_barrier_trigger/**"

mqtt-broker:
  - "mqtt_broker/**"

mqtt-listener:
  - "mqtt_listener/**"

nginx:
  - "nginx/**"

prometheus:
  - "prometheus/**"

sensor-connect:
  - "sensor_connect/**"

signal-light:
  - "signal_light/**"

storage-guard:
  - "storage_guard/**"

utils:
  - "utils/**"

webapp:
  - "inspect_webapp/**"
