name: pre-commit

on:
  push:
    branches: [ staging,"*code*","*github_action*","!dependabot/*" ]
  pull_request:
    branches: [ master,staging,"epic/*/*","!dependabot/*" ]
  merge_group:

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies and reformat code
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install
          # moved here to deal with error on github action
          pre-commit run --all-files
